name: Nightly release
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: 'Nightly release tag'
        required: true

jobs:
  create-nightly-tag:
    runs-on: ubuntu-20.04
    outputs:
      tag-name: ${{ steps.generate-tag.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - id: generate-tag
        run: |
          MANUAL_TAG="${{ inputs.tag-name }}"
          echo "TAG_NAME=${MANUAL_TAG:-$(date +'%Y-%m-%d')-a}" >> $GITHUB_OUTPUT
      - run: git tag "${{ steps.generate-tag.outputs.TAG_NAME }}"
      - run: git push origin "${{ steps.generate-tag.outputs.TAG_NAME }}"
  build-and-publish:
    needs: [create-nightly-tag]
    uses: ./.github/workflows/build.yml
    with:
      publish: true
      prerel_name: ${{ needs.create-nightly-tag.outputs.tag-name }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
