name: Release ruby.wasm
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: "Nightly release tag"
        required: true
  push:
    tags: ["*"]

jobs:
  create-nightly-tag:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      tag-name: ${{ steps.generate-tag.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - id: generate-tag
        run: |
          MANUAL_TAG="${{ inputs.tag-name }}"
          echo "TAG_NAME=${MANUAL_TAG:-$(date +'%Y-%m-%d')-a}" >> $GITHUB_OUTPUT
      - run: git tag "${{ steps.generate-tag.outputs.TAG_NAME }}"
      - run: git push origin "${{ steps.generate-tag.outputs.TAG_NAME }}"

  release-nightly:
    if: ${{ github.event_name != 'push' }}
    needs:
      - create-nightly-tag
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      publish: true
      prerel_name: ${{ needs.create-nightly-tag.outputs.tag-name }}
    secrets: inherit

  release-tag:
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      publish: true
      prerel_name: ${{ github.ref_name }}
    secrets: inherit
